ALTER TABLE page ADD CONSTRAINT FK_PAGE_ON_SITE FOREIGN KEY (site_id) REFERENCES site (id);
ALTER TABLE lemma ADD CONSTRAINT FK_LEMMA_ON_SITE FOREIGN KEY (site_id) REFERENCES site (id);
ALTER TABLE `index` ADD CONSTRAINT FK_INDEX_ON_LEMMA FOREIGN KEY (lemma_id) REFERENCES lemma (id);
ALTER TABLE `index` ADD CONSTRAINT FK_INDEX_ON_PAGE FOREIGN KEY (page_id) REFERENCES page (id);